import type { DesignTokens } from "../types";

export const PRESETS: Record<string, DesignTokens> = {
  "Classic Calle Nueve": {
    background: { color: "#F5E6C8", texture: "paper", opacity: 0.3 },
    colors: {
      pip: "#8B1A1A",
      pipSecondary: "#C49A2A",
      border: "#8B1A1A",
      divider: "#8B1A1A",
      index: "#1A1A1A",
      footer: "#8B1A1A",
      heroAccent: "#C49A2A",
      backBackground: "#8B1A1A",
      backAccent: "#C49A2A",
    },
    pips: {
      style: "cuban-icons",
      size: 80,
      spacing: 8,
      strokeWidth: 1.5,
      fillMode: "solid",
      symmetryLock: true,
    },
    divider: {
      type: "tobacco-leaf",
      thickness: 2,
      width: 0.85,
      ornament: "leaf",
      ornamentSize: 64,
    },
    border: {
      outerWidth: 8,
      innerWidth: 3,
      cornerDecorations: true,
      heroFrame: true,
    },
    typography: {
      indexFont: "Bebas Neue",
      footerFont: "Bebas Neue",
      indexSize: 40,
      footerSize: 18,
      tracking: 2,
    },
    footer: { text: "CALLE NUEVE", visible: true },
    back: {
      pattern: "mosaic",
      scale: 1,
      rotation: 0,
      centerMedallion: true,
      nonDirectionalCheck: true,
    },
  },

  "Vintage Havana": {
    background: { color: "#E8D5A3", texture: "grain", opacity: 0.4 },
    colors: {
      pip: "#5C3317",
      pipSecondary: "#B8860B",
      border: "#5C3317",
      divider: "#B8860B",
      index: "#2C1A0E",
      footer: "#5C3317",
      heroAccent: "#B8860B",
      backBackground: "#2C1A0E",
      backAccent: "#B8860B",
    },
    pips: {
      style: "cuban-icons",
      size: 76,
      spacing: 7,
      strokeWidth: 2,
      fillMode: "two-tone",
      symmetryLock: true,
    },
    divider: {
      type: "rope",
      thickness: 3,
      width: 0.9,
      ornament: "flourish",
      ornamentSize: 72,
    },
    border: {
      outerWidth: 10,
      innerWidth: 4,
      cornerDecorations: true,
      heroFrame: true,
    },
    typography: {
      indexFont: "Playfair Display",
      footerFont: "Playfair Display",
      indexSize: 38,
      footerSize: 16,
      tracking: 3,
    },
    footer: { text: "HABANA 1959", visible: true },
    back: {
      pattern: "art-deco",
      scale: 1.2,
      rotation: 45,
      centerMedallion: true,
      nonDirectionalCheck: true,
    },
  },

  "Miami Neon": {
    background: { color: "#0A0A1A", texture: "none", opacity: 1 },
    colors: {
      pip: "#FF006E",
      pipSecondary: "#00F5FF",
      border: "#FF006E",
      divider: "#00F5FF",
      index: "#FFFFFF",
      footer: "#FF006E",
      heroAccent: "#FFD600",
      backBackground: "#0A0A1A",
      backAccent: "#FF006E",
    },
    pips: {
      style: "rings",
      size: 72,
      spacing: 6,
      strokeWidth: 2.5,
      fillMode: "outline",
      symmetryLock: true,
    },
    divider: {
      type: "double-line",
      thickness: 2,
      width: 0.8,
      ornament: "diamond",
      ornamentSize: 56,
    },
    border: {
      outerWidth: 6,
      innerWidth: 2,
      cornerDecorations: false,
      heroFrame: true,
    },
    typography: {
      indexFont: "Bebas Neue",
      footerFont: "Bebas Neue",
      indexSize: 44,
      footerSize: 20,
      tracking: 6,
    },
    footer: { text: "MIAMI VICE", visible: true },
    back: {
      pattern: "sunburst",
      scale: 1,
      rotation: 0,
      centerMedallion: true,
      nonDirectionalCheck: true,
    },
  },

  "Wedding Gold": {
    background: { color: "#FFFDF5", texture: "paper", opacity: 0.2 },
    colors: {
      pip: "#C8A84B",
      pipSecondary: "#8B6914",
      border: "#C8A84B",
      divider: "#C8A84B",
      index: "#1A1400",
      footer: "#8B6914",
      heroAccent: "#FFD700",
      backBackground: "#1A1400",
      backAccent: "#C8A84B",
    },
    pips: {
      style: "diamonds",
      size: 68,
      spacing: 8,
      strokeWidth: 1,
      fillMode: "solid",
      symmetryLock: true,
    },
    divider: {
      type: "ornamental",
      thickness: 1.5,
      width: 0.75,
      ornament: "flourish",
      ornamentSize: 80,
    },
    border: {
      outerWidth: 12,
      innerWidth: 5,
      cornerDecorations: true,
      heroFrame: true,
    },
    typography: {
      indexFont: "Playfair Display",
      footerFont: "Playfair Display",
      indexSize: 36,
      footerSize: 14,
      tracking: 4,
    },
    footer: { text: "CALLE NUEVE", visible: true },
    back: {
      pattern: "diamonds",
      scale: 0.9,
      rotation: 45,
      centerMedallion: true,
      nonDirectionalCheck: true,
    },
  },

  "Art Deco Luxe": {
    background: { color: "#1C1C1C", texture: "none", opacity: 1 },
    colors: {
      pip: "#D4AF37",
      pipSecondary: "#E8E8E8",
      border: "#D4AF37",
      divider: "#D4AF37",
      index: "#F5F5F5",
      footer: "#D4AF37",
      heroAccent: "#D4AF37",
      backBackground: "#1C1C1C",
      backAccent: "#D4AF37",
    },
    pips: {
      style: "diamonds",
      size: 64,
      spacing: 7,
      strokeWidth: 1.5,
      fillMode: "solid",
      symmetryLock: true,
    },
    divider: {
      type: "art-deco",
      thickness: 2,
      width: 0.8,
      ornament: "sun",
      ornamentSize: 72,
    },
    border: {
      outerWidth: 8,
      innerWidth: 3,
      cornerDecorations: true,
      heroFrame: true,
    },
    typography: {
      indexFont: "Bebas Neue",
      footerFont: "Bebas Neue",
      indexSize: 42,
      footerSize: 18,
      tracking: 8,
    },
    footer: { text: "CALLE NUEVE", visible: true },
    back: {
      pattern: "art-deco",
      scale: 1,
      rotation: 0,
      centerMedallion: true,
      nonDirectionalCheck: true,
    },
  },

  "Souvenir Edition": {
    background: { color: "#F0F4E8", texture: "paper", opacity: 0.25 },
    colors: {
      pip: "#2D5016",
      pipSecondary: "#8B6914",
      border: "#2D5016",
      divider: "#8B6914",
      index: "#1A1A1A",
      footer: "#2D5016",
      heroAccent: "#8B6914",
      backBackground: "#2D5016",
      backAccent: "#F0F4E8",
    },
    pips: {
      style: "cuban-icons",
      size: 72,
      spacing: 6,
      strokeWidth: 1.5,
      fillMode: "solid",
      symmetryLock: true,
    },
    divider: {
      type: "tobacco-leaf",
      thickness: 2,
      width: 0.85,
      ornament: "leaf",
      ornamentSize: 68,
    },
    border: {
      outerWidth: 9,
      innerWidth: 3,
      cornerDecorations: true,
      heroFrame: true,
    },
    typography: {
      indexFont: "Playfair Display",
      footerFont: "Playfair Display",
      indexSize: 38,
      footerSize: 16,
      tracking: 2,
    },
    footer: { text: "CUBA LIBRE", visible: true },
    back: {
      pattern: "mosaic",
      scale: 1,
      rotation: 0,
      centerMedallion: true,
      nonDirectionalCheck: true,
    },
  },

  "Minimal Modern": {
    background: { color: "#FAFAFA", texture: "none", opacity: 1 },
    colors: {
      pip: "#1A1A1A",
      pipSecondary: "#666666",
      border: "#1A1A1A",
      divider: "#CCCCCC",
      index: "#1A1A1A",
      footer: "#999999",
      heroAccent: "#1A1A1A",
      backBackground: "#1A1A1A",
      backAccent: "#F5F5F5",
    },
    pips: {
      style: "classic-dots",
      size: 60,
      spacing: 6,
      strokeWidth: 0,
      fillMode: "solid",
      symmetryLock: true,
    },
    divider: {
      type: "straight",
      thickness: 1,
      width: 0.7,
      ornament: "none",
      ornamentSize: 0,
    },
    border: {
      outerWidth: 4,
      innerWidth: 0,
      cornerDecorations: false,
      heroFrame: false,
    },
    typography: {
      indexFont: "system",
      footerFont: "system",
      indexSize: 36,
      footerSize: 14,
      tracking: 0,
    },
    footer: { text: "CALLE NUEVE", visible: true },
    back: {
      pattern: "plain",
      scale: 1,
      rotation: 0,
      centerMedallion: false,
      nonDirectionalCheck: true,
    },
  },

  // Corporate gift theme: white tile, big flat black dots, one accent bar with a
  // spinner, corner index only (no footer). Per client: change the divider/back
  // accent and add a logo.
  "Clean": {
    background: { color: "#FFFFFF", texture: "none", opacity: 1 },
    colors: {
      pip: "#111111",
      pipSecondary: "#111111",
      border: "#111111",
      divider: "#E5097F",
      index: "#111111",
      footer: "#111111",
      heroAccent: "#E5097F",
      backBackground: "#E5097F",
      backAccent: "#FFFFFF",
    },
    pips: {
      style: "classic-dots",
      size: 118,
      spacing: 8,
      spread: 24,
      strokeWidth: 0,
      fillMode: "solid",
      symmetryLock: true,
      flat: true,
    },
    divider: {
      type: "bar",
      thickness: 18,
      width: 0.96,
      ornament: "spinner",
      ornamentSize: 34,
    },
    border: {
      outerWidth: 0,
      innerWidth: 0,
      cornerDecorations: false,
      heroFrame: false,
    },
    typography: {
      indexFont: "Bebas Neue",
      footerFont: "Bebas Neue",
      indexSize: 34,
      footerSize: 14,
      tracking: 0,
      indexVisible: true,
    },
    footer: { text: "", visible: false },
    back: {
      pattern: "plain",
      scale: 1,
      rotation: 0,
      centerMedallion: false,
      nonDirectionalCheck: true,
      frame: false,
    },
  },

  // Souvenir line (2026-09-21). Little Havana deck: cream tiles with tobacco Cuban
  // icons, terracotta divider, a Cuban hydraulic-tile back and a cigar-label box.
  "Domino Park": {
    background: { color: "#F5EBD6", texture: "paper", opacity: 0.25 },
    colors: {
      pip: "#4A2E1A",
      pipSecondary: "#B5442F",
      border: "#4A2E1A",
      divider: "#B5442F",
      index: "#4A2E1A",
      footer: "#B5442F",
      heroAccent: "#B5442F",
      backBackground: "#F1E6CF",
      backAccent: "#1E5A46",
      backSecondary: "#B5442F",
      backTertiary: "#C9A14A",
    },
    pips: {
      style: "cuban-icons",
      size: 80,
      spacing: 8,
      strokeWidth: 1.5,
      fillMode: "two-tone",
      symmetryLock: true,
    },
    divider: {
      type: "tobacco-leaf",
      thickness: 2.5,
      width: 0.85,
      ornament: "leaf",
      ornamentSize: 64,
    },
    border: {
      outerWidth: 7,
      innerWidth: 2,
      cornerDecorations: true,
      heroFrame: true,
    },
    typography: {
      indexFont: "Bebas Neue",
      footerFont: "Bebas Neue",
      indexSize: 38,
      footerSize: 16,
      tracking: 4,
      indexVisible: true,
    },
    footer: { text: "LITTLE HAVANA · MIAMI", visible: true },
    back: {
      pattern: "cuban-tile",
      scale: 1,
      rotation: 0,
      centerMedallion: true,
      medallionStyle: "tile",
      nonDirectionalCheck: true,
      frame: true,
    },
    tuckBox: {
      frontStyle: "cartouche",
      frontColor: "#F1E6CF",
      title: "DOMINO PARK",
      subtitle: "LITTLE HAVANA · MIAMI",
      tagline: "55 CARTAS · DOBLE NUEVE",
      tagline2: "55 CARDS · DOUBLE NINE",
      edition: "SOUVENIR EDITION",
      url: "CALLENUEVE.COM",
      backText:
        "Every afternoon at Domino Park on Calle Ocho, the tiles slap the tables and the cafecito is strong. This deck is that game, in your pocket.\nCada tarde en el Parque del Dominó, las fichas suenan y el cafecito es fuerte. Este mazo es ese juego, en tu bolsillo.\nScan the last card to learn the game in two minutes.",
      showIcons: false,
      showDieline: true,
    },
  },

  // South Beach deck: white tiles, flat navy dots, one flamingo bar, a stepped
  // sunburst back with a porthole, and a silver-foil label box.
  "Deco Beach": {
    background: { color: "#FFFFFF", texture: "none", opacity: 1 },
    colors: {
      pip: "#1D3557",
      pipSecondary: "#1D3557",
      border: "#1D3557",
      divider: "#F4A7B9",
      index: "#1D3557",
      footer: "#1D3557",
      heroAccent: "#F4A7B9",
      backBackground: "#8FD3C7",
      backAccent: "#1D3557",
      backSecondary: "#F4A7B9",
      backTertiary: "#F6E7C1",
    },
    pips: {
      style: "classic-dots",
      size: 118,
      spacing: 8,
      spread: 24,
      strokeWidth: 0,
      fillMode: "solid",
      symmetryLock: true,
      flat: true,
    },
    divider: {
      type: "bar",
      thickness: 18,
      width: 0.96,
      ornament: "spinner",
      ornamentSize: 34,
    },
    border: {
      outerWidth: 0,
      innerWidth: 0,
      cornerDecorations: false,
      heroFrame: false,
    },
    typography: {
      indexFont: "Bebas Neue",
      footerFont: "Bebas Neue",
      indexSize: 34,
      footerSize: 14,
      tracking: 0,
      indexVisible: true,
    },
    footer: { text: "", visible: false },
    back: {
      pattern: "deco-rays",
      scale: 1,
      rotation: 0,
      centerMedallion: true,
      medallionStyle: "porthole",
      nonDirectionalCheck: true,
      frame: true,
    },
    tuckBox: {
      frontStyle: "cartouche",
      frontColor: "#F6E7C1",
      title: "DECO BEACH",
      subtitle: "MIAMI BEACH",
      tagline: "55 CARDS · DOUBLE NINE",
      tagline2: "55 CARTAS · DOBLE NUEVE",
      edition: "SOUVENIR EDITION",
      url: "CALLENUEVE.COM",
      backText:
        "Pastel hotels, porthole windows and a sunburst over every door. Ocean Drive, in a deck of domino cards.\nHoteles pastel, ventanas de ojo de buey y un sol sobre cada puerta. Ocean Drive, en un mazo de cartas de dominó.\nScan the last card to learn the game in two minutes.",
      showIcons: false,
      showDieline: true,
    },
  },

  // Retro Miami sunset deck (2026-09-21): cream tiles with flat navy dots and a
  // coral bar, a symmetric sunset back with a banded sun and palm silhouettes,
  // sand label box with a flamingo stamp.
  "Miami Sunset": {
    background: { color: "#FFF6E5", texture: "none", opacity: 1 },
    colors: {
      pip: "#2A1B4E",
      pipSecondary: "#2A1B4E",
      border: "#2A1B4E",
      divider: "#FF5FA8",
      index: "#2A1B4E",
      footer: "#2A1B4E",
      heroAccent: "#FF5FA8",
      backBackground: "#24C6C4",
      backAccent: "#2A1B4E",
      backSecondary: "#FF5FA8",
      backTertiary: "#FFD59E",
    },
    pips: {
      style: "classic-dots",
      size: 118,
      spacing: 8,
      spread: 24,
      strokeWidth: 0,
      fillMode: "solid",
      symmetryLock: true,
      flat: true,
    },
    divider: {
      type: "bar",
      thickness: 18,
      width: 0.96,
      ornament: "spinner",
      ornamentSize: 34,
    },
    border: {
      outerWidth: 0,
      innerWidth: 0,
      cornerDecorations: false,
      heroFrame: false,
    },
    typography: {
      indexFont: "Bebas Neue",
      footerFont: "Bebas Neue",
      indexSize: 34,
      footerSize: 14,
      tracking: 0,
      indexVisible: true,
    },
    footer: { text: "", visible: false },
    back: {
      pattern: "miami-sunset",
      scale: 1,
      rotation: 0,
      centerMedallion: false,
      nonDirectionalCheck: true,
      frame: false,
    },
    tuckBox: {
      frontStyle: "cartouche",
      frontColor: "#FFF6E5",
      title: "MIAMI SUNSET",
      subtitle: "MIAMI · FLORIDA",
      tagline: "55 CARDS · DOUBLE NINE",
      tagline2: "55 CARTAS · DOBLE NUEVE",
      edition: "SOUVENIR EDITION",
      url: "CALLENUEVE.COM",
      backText:
        "Palms, a sunset and a game of dominoes. Miami, in your pocket.\nPalmas, un atardecer y una partida de dominó. Miami, en tu bolsillo.\nScan the last card to learn the game in two minutes.",
      showIcons: false,
      showDieline: true,
    },
  },

  // Vintage flamingo trading card (2026-09-21): cream tiles, deep teal dots, gold
  // bar; a one-way back drawn like a 1910s tobacco card with a flamingo in gold
  // reeds; gold label box.
  "Flamingo Card": {
    background: { color: "#F6EBD3", texture: "paper", opacity: 0.2 },
    colors: {
      pip: "#1E4E52",
      pipSecondary: "#1E4E52",
      border: "#1E4E52",
      divider: "#C9A14A",
      index: "#1E4E52",
      footer: "#1E4E52",
      heroAccent: "#E8456B",
      backBackground: "#F3E6C8",
      backAccent: "#C9A14A",
      backSecondary: "#E8456B",
      backTertiary: "#5FB3B8",
    },
    pips: {
      style: "classic-dots",
      size: 118,
      spacing: 8,
      spread: 24,
      strokeWidth: 0,
      fillMode: "solid",
      symmetryLock: true,
      flat: true,
    },
    divider: {
      type: "bar",
      thickness: 18,
      width: 0.96,
      ornament: "spinner",
      ornamentSize: 34,
    },
    border: {
      outerWidth: 0,
      innerWidth: 0,
      cornerDecorations: false,
      heroFrame: false,
    },
    typography: {
      indexFont: "Bebas Neue",
      footerFont: "Bebas Neue",
      indexSize: 34,
      footerSize: 14,
      tracking: 0,
      indexVisible: true,
    },
    footer: { text: "", visible: false },
    back: {
      pattern: "flamingo-card",
      scale: 1,
      rotation: 0,
      centerMedallion: false,
      nonDirectionalCheck: false,
      frame: false,
      label: "MIAMI · FLORIDA",
    },
    tuckBox: {
      frontStyle: "cartouche",
      frontColor: "#F6EBD3",
      title: "FLAMINGO",
      subtitle: "MIAMI · FLORIDA",
      tagline: "55 CARDS · DOUBLE NINE",
      tagline2: "55 CARTAS · DOBLE NUEVE",
      edition: "SOUVENIR EDITION",
      url: "CALLENUEVE.COM",
      backText:
        "A flamingo in the reeds, the way the old trading cards drew it. Miami, in your pocket.\nUn flamenco entre los juncos, como en las tarjetas antiguas. Miami, en tu bolsillo.\nScan the last card to learn the game in two minutes.",
      showIcons: false,
      showDieline: true,
    },
  },
};

export const PRESET_NAMES = Object.keys(PRESETS);
