import type { DesignTokens } from "../types";

export const PRESETS: Record<string, DesignTokens> = {
  "Classic Calle Nueve": {
    background: { color: "#F5E6C8", texture: "paper", opacity: 0.3 },
    colors: {
      pip: "#8B1A1A",
      pipSecondary: "#C49A2A",
      border: "#8B1A1A",
      divider: "#8B1A1A",
      index: "#1A1A1A",
      footer: "#8B1A1A",
      heroAccent: "#C49A2A",
      backBackground: "#8B1A1A",
      backAccent: "#C49A2A",
    },
    pips: {
      style: "cuban-icons",
      size: 80,
      spacing: 8,
      strokeWidth: 1.5,
      fillMode: "solid",
      symmetryLock: true,
    },
    divider: {
      type: "tobacco-leaf",
      thickness: 2,
      width: 0.85,
      ornament: "leaf",
      ornamentSize: 24,
    },
    border: {
      outerWidth: 8,
      innerWidth: 3,
      cornerDecorations: true,
      heroFrame: true,
    },
    typography: {
      indexFont: "Bebas Neue",
      footerFont: "Bebas Neue",
      indexSize: 40,
      footerSize: 18,
      tracking: 2,
    },
    footer: { text: "CALLE NUEVE", visible: true },
    back: {
      pattern: "mosaic",
      scale: 1,
      rotation: 0,
      centerMedallion: true,
      nonDirectionalCheck: true,
    },
  },

  "Vintage Havana": {
    background: { color: "#E8D5A3", texture: "grain", opacity: 0.4 },
    colors: {
      pip: "#5C3317",
      pipSecondary: "#B8860B",
      border: "#5C3317",
      divider: "#B8860B",
      index: "#2C1A0E",
      footer: "#5C3317",
      heroAccent: "#B8860B",
      backBackground: "#2C1A0E",
      backAccent: "#B8860B",
    },
    pips: {
      style: "cuban-icons",
      size: 76,
      spacing: 7,
      strokeWidth: 2,
      fillMode: "two-tone",
      symmetryLock: true,
    },
    divider: {
      type: "rope",
      thickness: 3,
      width: 0.9,
      ornament: "flourish",
      ornamentSize: 28,
    },
    border: {
      outerWidth: 10,
      innerWidth: 4,
      cornerDecorations: true,
      heroFrame: true,
    },
    typography: {
      indexFont: "Playfair Display",
      footerFont: "Playfair Display",
      indexSize: 38,
      footerSize: 16,
      tracking: 3,
    },
    footer: { text: "HABANA 1959", visible: true },
    back: {
      pattern: "art-deco",
      scale: 1.2,
      rotation: 45,
      centerMedallion: true,
      nonDirectionalCheck: true,
    },
  },

  "Miami Neon": {
    background: { color: "#0A0A1A", texture: "none", opacity: 1 },
    colors: {
      pip: "#FF006E",
      pipSecondary: "#00F5FF",
      border: "#FF006E",
      divider: "#00F5FF",
      index: "#FFFFFF",
      footer: "#FF006E",
      heroAccent: "#FFD600",
      backBackground: "#0A0A1A",
      backAccent: "#FF006E",
    },
    pips: {
      style: "rings",
      size: 72,
      spacing: 6,
      strokeWidth: 2.5,
      fillMode: "outline",
      symmetryLock: true,
    },
    divider: {
      type: "double-line",
      thickness: 2,
      width: 0.8,
      ornament: "diamond",
      ornamentSize: 20,
    },
    border: {
      outerWidth: 6,
      innerWidth: 2,
      cornerDecorations: false,
      heroFrame: true,
    },
    typography: {
      indexFont: "Bebas Neue",
      footerFont: "Bebas Neue",
      indexSize: 44,
      footerSize: 20,
      tracking: 6,
    },
    footer: { text: "MIAMI VICE", visible: true },
    back: {
      pattern: "sunburst",
      scale: 1,
      rotation: 0,
      centerMedallion: true,
      nonDirectionalCheck: true,
    },
  },

  "Wedding Gold": {
    background: { color: "#FFFDF5", texture: "paper", opacity: 0.2 },
    colors: {
      pip: "#C8A84B",
      pipSecondary: "#8B6914",
      border: "#C8A84B",
      divider: "#C8A84B",
      index: "#1A1400",
      footer: "#8B6914",
      heroAccent: "#FFD700",
      backBackground: "#1A1400",
      backAccent: "#C8A84B",
    },
    pips: {
      style: "diamonds",
      size: 68,
      spacing: 8,
      strokeWidth: 1,
      fillMode: "solid",
      symmetryLock: true,
    },
    divider: {
      type: "ornamental",
      thickness: 1.5,
      width: 0.75,
      ornament: "flourish",
      ornamentSize: 32,
    },
    border: {
      outerWidth: 12,
      innerWidth: 5,
      cornerDecorations: true,
      heroFrame: true,
    },
    typography: {
      indexFont: "Playfair Display",
      footerFont: "Playfair Display",
      indexSize: 36,
      footerSize: 14,
      tracking: 4,
    },
    footer: { text: "CALLE NUEVE", visible: true },
    back: {
      pattern: "diamonds",
      scale: 0.9,
      rotation: 45,
      centerMedallion: true,
      nonDirectionalCheck: true,
    },
  },

  "Art Deco Luxe": {
    background: { color: "#1C1C1C", texture: "none", opacity: 1 },
    colors: {
      pip: "#D4AF37",
      pipSecondary: "#E8E8E8",
      border: "#D4AF37",
      divider: "#D4AF37",
      index: "#F5F5F5",
      footer: "#D4AF37",
      heroAccent: "#D4AF37",
      backBackground: "#1C1C1C",
      backAccent: "#D4AF37",
    },
    pips: {
      style: "diamonds",
      size: 64,
      spacing: 7,
      strokeWidth: 1.5,
      fillMode: "solid",
      symmetryLock: true,
    },
    divider: {
      type: "art-deco",
      thickness: 2,
      width: 0.8,
      ornament: "sun",
      ornamentSize: 28,
    },
    border: {
      outerWidth: 8,
      innerWidth: 3,
      cornerDecorations: true,
      heroFrame: true,
    },
    typography: {
      indexFont: "Bebas Neue",
      footerFont: "Bebas Neue",
      indexSize: 42,
      footerSize: 18,
      tracking: 8,
    },
    footer: { text: "CALLE NUEVE", visible: true },
    back: {
      pattern: "art-deco",
      scale: 1,
      rotation: 0,
      centerMedallion: true,
      nonDirectionalCheck: true,
    },
  },

  "Souvenir Edition": {
    background: { color: "#F0F4E8", texture: "paper", opacity: 0.25 },
    colors: {
      pip: "#2D5016",
      pipSecondary: "#8B6914",
      border: "#2D5016",
      divider: "#8B6914",
      index: "#1A1A1A",
      footer: "#2D5016",
      heroAccent: "#8B6914",
      backBackground: "#2D5016",
      backAccent: "#F0F4E8",
    },
    pips: {
      style: "cuban-icons",
      size: 72,
      spacing: 6,
      strokeWidth: 1.5,
      fillMode: "solid",
      symmetryLock: true,
    },
    divider: {
      type: "tobacco-leaf",
      thickness: 2,
      width: 0.85,
      ornament: "leaf",
      ornamentSize: 26,
    },
    border: {
      outerWidth: 9,
      innerWidth: 3,
      cornerDecorations: true,
      heroFrame: true,
    },
    typography: {
      indexFont: "Playfair Display",
      footerFont: "Playfair Display",
      indexSize: 38,
      footerSize: 16,
      tracking: 2,
    },
    footer: { text: "CUBA LIBRE", visible: true },
    back: {
      pattern: "mosaic",
      scale: 1,
      rotation: 0,
      centerMedallion: true,
      nonDirectionalCheck: true,
    },
  },

  "Minimal Modern": {
    background: { color: "#FAFAFA", texture: "none", opacity: 1 },
    colors: {
      pip: "#1A1A1A",
      pipSecondary: "#666666",
      border: "#1A1A1A",
      divider: "#CCCCCC",
      index: "#1A1A1A",
      footer: "#999999",
      heroAccent: "#1A1A1A",
      backBackground: "#1A1A1A",
      backAccent: "#F5F5F5",
    },
    pips: {
      style: "classic-dots",
      size: 60,
      spacing: 6,
      strokeWidth: 0,
      fillMode: "solid",
      symmetryLock: true,
    },
    divider: {
      type: "straight",
      thickness: 1,
      width: 0.7,
      ornament: "none",
      ornamentSize: 0,
    },
    border: {
      outerWidth: 4,
      innerWidth: 0,
      cornerDecorations: false,
      heroFrame: false,
    },
    typography: {
      indexFont: "system",
      footerFont: "system",
      indexSize: 36,
      footerSize: 14,
      tracking: 0,
    },
    footer: { text: "CALLE NUEVE", visible: true },
    back: {
      pattern: "plain",
      scale: 1,
      rotation: 0,
      centerMedallion: false,
      nonDirectionalCheck: true,
    },
  },
};

export const PRESET_NAMES = Object.keys(PRESETS);
